// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: mpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MpcSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UnsignedTxHex string                 `protobuf:"bytes,2,opt,name=unsigned_tx_hex,json=unsignedTxHex,proto3" json:"unsigned_tx_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpcSignRequest) Reset() {
	*x = MpcSignRequest{}
	mi := &file_mpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpcSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpcSignRequest) ProtoMessage() {}

func (x *MpcSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpcSignRequest.ProtoReflect.Descriptor instead.
func (*MpcSignRequest) Descriptor() ([]byte, []int) {
	return file_mpc_proto_rawDescGZIP(), []int{0}
}

func (x *MpcSignRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *MpcSignRequest) GetUnsignedTxHex() string {
	if x != nil {
		return x.UnsignedTxHex
	}
	return ""
}

type MpcSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedTxHex   string                 `protobuf:"bytes,1,opt,name=signed_tx_hex,json=signedTxHex,proto3" json:"signed_tx_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpcSignResponse) Reset() {
	*x = MpcSignResponse{}
	mi := &file_mpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpcSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpcSignResponse) ProtoMessage() {}

func (x *MpcSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpcSignResponse.ProtoReflect.Descriptor instead.
func (*MpcSignResponse) Descriptor() ([]byte, []int) {
	return file_mpc_proto_rawDescGZIP(), []int{1}
}

func (x *MpcSignResponse) GetSignedTxHex() string {
	if x != nil {
		return x.SignedTxHex
	}
	return ""
}

var File_mpc_proto protoreflect.FileDescriptor

const file_mpc_proto_rawDesc = "" +
	"\n" +
	"\tmpc.proto\x12\x06mpc.v1\"M\n" +
	"\x0eMpcSignRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12&\n" +
	"\x0funsigned_tx_hex\x18\x02 \x01(\tR\runsignedTxHex\"5\n" +
	"\x0fMpcSignResponse\x12\"\n" +
	"\rsigned_tx_hex\x18\x01 \x01(\tR\vsignedTxHex2L\n" +
	"\x11MpcSigningService\x127\n" +
	"\x04Sign\x12\x16.mpc.v1.MpcSignRequest\x1a\x17.mpc.v1.MpcSignResponseBIZGgithub.com/ai-crypto-onramp/transaction-orchestrator/internal/pb/mpc;pbb\x06proto3"

var (
	file_mpc_proto_rawDescOnce sync.Once
	file_mpc_proto_rawDescData []byte
)

func file_mpc_proto_rawDescGZIP() []byte {
	file_mpc_proto_rawDescOnce.Do(func() {
		file_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_proto_rawDesc), len(file_mpc_proto_rawDesc)))
	})
	return file_mpc_proto_rawDescData
}

var file_mpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mpc_proto_goTypes = []any{
	(*MpcSignRequest)(nil),  // 0: mpc.v1.MpcSignRequest
	(*MpcSignResponse)(nil), // 1: mpc.v1.MpcSignResponse
}
var file_mpc_proto_depIdxs = []int32{
	0, // 0: mpc.v1.MpcSigningService.Sign:input_type -> mpc.v1.MpcSignRequest
	1, // 1: mpc.v1.MpcSigningService.Sign:output_type -> mpc.v1.MpcSignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpc_proto_init() }
func file_mpc_proto_init() {
	if File_mpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_proto_rawDesc), len(file_mpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpc_proto_goTypes,
		DependencyIndexes: file_mpc_proto_depIdxs,
		MessageInfos:      file_mpc_proto_msgTypes,
	}.Build()
	File_mpc_proto = out.File
	file_mpc_proto_goTypes = nil
	file_mpc_proto_depIdxs = nil
}
