// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: mpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MpcSigningService_Sign_FullMethodName = "/mpc.v1.MpcSigningService/Sign"
)

// MpcSigningServiceClient is the client API for MpcSigningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MpcSigningService threshold-signs a transaction payload.
type MpcSigningServiceClient interface {
	Sign(ctx context.Context, in *MpcSignRequest, opts ...grpc.CallOption) (*MpcSignResponse, error)
}

type mpcSigningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMpcSigningServiceClient(cc grpc.ClientConnInterface) MpcSigningServiceClient {
	return &mpcSigningServiceClient{cc}
}

func (c *mpcSigningServiceClient) Sign(ctx context.Context, in *MpcSignRequest, opts ...grpc.CallOption) (*MpcSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MpcSignResponse)
	err := c.cc.Invoke(ctx, MpcSigningService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MpcSigningServiceServer is the server API for MpcSigningService service.
// All implementations must embed UnimplementedMpcSigningServiceServer
// for forward compatibility.
//
// MpcSigningService threshold-signs a transaction payload.
type MpcSigningServiceServer interface {
	Sign(context.Context, *MpcSignRequest) (*MpcSignResponse, error)
	mustEmbedUnimplementedMpcSigningServiceServer()
}

// UnimplementedMpcSigningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMpcSigningServiceServer struct{}

func (UnimplementedMpcSigningServiceServer) Sign(context.Context, *MpcSignRequest) (*MpcSignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedMpcSigningServiceServer) mustEmbedUnimplementedMpcSigningServiceServer() {}
func (UnimplementedMpcSigningServiceServer) testEmbeddedByValue()                           {}

// UnsafeMpcSigningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MpcSigningServiceServer will
// result in compilation errors.
type UnsafeMpcSigningServiceServer interface {
	mustEmbedUnimplementedMpcSigningServiceServer()
}

func RegisterMpcSigningServiceServer(s grpc.ServiceRegistrar, srv MpcSigningServiceServer) {
	// If the following call panics, it indicates UnimplementedMpcSigningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MpcSigningService_ServiceDesc, srv)
}

func _MpcSigningService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MpcSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSigningServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpcSigningService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSigningServiceServer).Sign(ctx, req.(*MpcSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MpcSigningService_ServiceDesc is the grpc.ServiceDesc for MpcSigningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MpcSigningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MpcSigningService",
	HandlerType: (*MpcSigningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _MpcSigningService_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc.proto",
}
