// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: blockchain.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockchainGateway_Broadcast_FullMethodName = "/blockchain.v1.BlockchainGateway/Broadcast"
	BlockchainGateway_Status_FullMethodName    = "/blockchain.v1.BlockchainGateway/Status"
)

// BlockchainGatewayClient is the client API for BlockchainGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlockchainGateway broadcasts a signed transaction and reports its
// on-chain status.
type BlockchainGatewayClient interface {
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
}

type blockchainGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainGatewayClient(cc grpc.ClientConnInterface) BlockchainGatewayClient {
	return &blockchainGatewayClient{cc}
}

func (c *blockchainGatewayClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, BlockchainGateway_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainGatewayClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, BlockchainGateway_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainGatewayServer is the server API for BlockchainGateway service.
// All implementations must embed UnimplementedBlockchainGatewayServer
// for forward compatibility.
//
// BlockchainGateway broadcasts a signed transaction and reports its
// on-chain status.
type BlockchainGatewayServer interface {
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	Status(context.Context, *StatusRequest) (*BroadcastResponse, error)
	mustEmbedUnimplementedBlockchainGatewayServer()
}

// UnimplementedBlockchainGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockchainGatewayServer struct{}

func (UnimplementedBlockchainGatewayServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedBlockchainGatewayServer) Status(context.Context, *StatusRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedBlockchainGatewayServer) mustEmbedUnimplementedBlockchainGatewayServer() {}
func (UnimplementedBlockchainGatewayServer) testEmbeddedByValue()                           {}

// UnsafeBlockchainGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainGatewayServer will
// result in compilation errors.
type UnsafeBlockchainGatewayServer interface {
	mustEmbedUnimplementedBlockchainGatewayServer()
}

func RegisterBlockchainGatewayServer(s grpc.ServiceRegistrar, srv BlockchainGatewayServer) {
	// If the following call panics, it indicates UnimplementedBlockchainGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockchainGateway_ServiceDesc, srv)
}

func _BlockchainGateway_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainGatewayServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainGateway_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainGatewayServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainGateway_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainGatewayServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainGateway_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainGatewayServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockchainGateway_ServiceDesc is the grpc.ServiceDesc for BlockchainGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.v1.BlockchainGateway",
	HandlerType: (*BlockchainGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _BlockchainGateway_Broadcast_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _BlockchainGateway_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}
