// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: kyt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KytRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DestAddress   string                 `protobuf:"bytes,3,opt,name=dest_address,json=destAddress,proto3" json:"dest_address,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KytRequest) Reset() {
	*x = KytRequest{}
	mi := &file_kyt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KytRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KytRequest) ProtoMessage() {}

func (x *KytRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KytRequest.ProtoReflect.Descriptor instead.
func (*KytRequest) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{0}
}

func (x *KytRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *KytRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KytRequest) GetDestAddress() string {
	if x != nil {
		return x.DestAddress
	}
	return ""
}

func (x *KytRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *KytRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type KytResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"` // "clear" | "review" | "reject"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KytResponse) Reset() {
	*x = KytResponse{}
	mi := &file_kyt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KytResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KytResponse) ProtoMessage() {}

func (x *KytResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KytResponse.ProtoReflect.Descriptor instead.
func (*KytResponse) Descriptor() ([]byte, []int) {
	return file_kyt_proto_rawDescGZIP(), []int{1}
}

func (x *KytResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *KytResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_kyt_proto protoreflect.FileDescriptor

const file_kyt_proto_rawDesc = "" +
	"\n" +
	"\tkyt.proto\x12\x06kyt.v1\"\x8b\x01\n" +
	"\n" +
	"KytRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdest_address\x18\x03 \x01(\tR\vdestAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x05 \x01(\tR\x05asset\"A\n" +
	"\vKytResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2D\n" +
	"\x0fAmlKytScreening\x121\n" +
	"\x06Screen\x12\x12.kyt.v1.KytRequest\x1a\x13.kyt.v1.KytResponseBIZGgithub.com/ai-crypto-onramp/transaction-orchestrator/internal/pb/kyt;pbb\x06proto3"

var (
	file_kyt_proto_rawDescOnce sync.Once
	file_kyt_proto_rawDescData []byte
)

func file_kyt_proto_rawDescGZIP() []byte {
	file_kyt_proto_rawDescOnce.Do(func() {
		file_kyt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyt_proto_rawDesc), len(file_kyt_proto_rawDesc)))
	})
	return file_kyt_proto_rawDescData
}

var file_kyt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kyt_proto_goTypes = []any{
	(*KytRequest)(nil),  // 0: kyt.v1.KytRequest
	(*KytResponse)(nil), // 1: kyt.v1.KytResponse
}
var file_kyt_proto_depIdxs = []int32{
	0, // 0: kyt.v1.AmlKytScreening.Screen:input_type -> kyt.v1.KytRequest
	1, // 1: kyt.v1.AmlKytScreening.Screen:output_type -> kyt.v1.KytResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kyt_proto_init() }
func file_kyt_proto_init() {
	if File_kyt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyt_proto_rawDesc), len(file_kyt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyt_proto_goTypes,
		DependencyIndexes: file_kyt_proto_depIdxs,
		MessageInfos:      file_kyt_proto_msgTypes,
	}.Build()
	File_kyt_proto = out.File
	file_kyt_proto_goTypes = nil
	file_kyt_proto_depIdxs = nil
}
