// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: kyt.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmlKytScreening_Screen_FullMethodName = "/kyt.v1.AmlKytScreening/Screen"
)

// AmlKytScreeningClient is the client API for AmlKytScreening service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AmlKytScreening screens the destination address / transaction for AML/KYT
// risk.
type AmlKytScreeningClient interface {
	Screen(ctx context.Context, in *KytRequest, opts ...grpc.CallOption) (*KytResponse, error)
}

type amlKytScreeningClient struct {
	cc grpc.ClientConnInterface
}

func NewAmlKytScreeningClient(cc grpc.ClientConnInterface) AmlKytScreeningClient {
	return &amlKytScreeningClient{cc}
}

func (c *amlKytScreeningClient) Screen(ctx context.Context, in *KytRequest, opts ...grpc.CallOption) (*KytResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KytResponse)
	err := c.cc.Invoke(ctx, AmlKytScreening_Screen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmlKytScreeningServer is the server API for AmlKytScreening service.
// All implementations must embed UnimplementedAmlKytScreeningServer
// for forward compatibility.
//
// AmlKytScreening screens the destination address / transaction for AML/KYT
// risk.
type AmlKytScreeningServer interface {
	Screen(context.Context, *KytRequest) (*KytResponse, error)
	mustEmbedUnimplementedAmlKytScreeningServer()
}

// UnimplementedAmlKytScreeningServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmlKytScreeningServer struct{}

func (UnimplementedAmlKytScreeningServer) Screen(context.Context, *KytRequest) (*KytResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screen not implemented")
}
func (UnimplementedAmlKytScreeningServer) mustEmbedUnimplementedAmlKytScreeningServer() {}
func (UnimplementedAmlKytScreeningServer) testEmbeddedByValue()                         {}

// UnsafeAmlKytScreeningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmlKytScreeningServer will
// result in compilation errors.
type UnsafeAmlKytScreeningServer interface {
	mustEmbedUnimplementedAmlKytScreeningServer()
}

func RegisterAmlKytScreeningServer(s grpc.ServiceRegistrar, srv AmlKytScreeningServer) {
	// If the following call panics, it indicates UnimplementedAmlKytScreeningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmlKytScreening_ServiceDesc, srv)
}

func _AmlKytScreening_Screen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KytRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmlKytScreeningServer).Screen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmlKytScreening_Screen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmlKytScreeningServer).Screen(ctx, req.(*KytRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AmlKytScreening_ServiceDesc is the grpc.ServiceDesc for AmlKytScreening service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmlKytScreening_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyt.v1.AmlKytScreening",
	HandlerType: (*AmlKytScreeningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Screen",
			Handler:    _AmlKytScreening_Screen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyt.proto",
}
