// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Rail          string                 `protobuf:"bytes,5,opt,name=rail,proto3" json:"rail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerPostRequest) Reset() {
	*x = LedgerPostRequest{}
	mi := &file_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPostRequest) ProtoMessage() {}

func (x *LedgerPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPostRequest.ProtoReflect.Descriptor instead.
func (*LedgerPostRequest) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerPostRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *LedgerPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LedgerPostRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LedgerPostRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *LedgerPostRequest) GetRail() string {
	if x != nil {
		return x.Rail
	}
	return ""
}

type LedgerPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JournalId     string                 `protobuf:"bytes,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerPostResponse) Reset() {
	*x = LedgerPostResponse{}
	mi := &file_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerPostResponse) ProtoMessage() {}

func (x *LedgerPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerPostResponse.ProtoReflect.Descriptor instead.
func (*LedgerPostResponse) Descriptor() ([]byte, []int) {
	return file_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerPostResponse) GetJournalId() string {
	if x != nil {
		return x.JournalId
	}
	return ""
}

var File_ledger_proto protoreflect.FileDescriptor

const file_ledger_proto_rawDesc = "" +
	"\n" +
	"\fledger.proto\x12\tledger.v1\"\x83\x01\n" +
	"\x11LedgerPostRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x12\n" +
	"\x04rail\x18\x05 \x01(\tR\x04rail\"3\n" +
	"\x12LedgerPostResponse\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x01 \x01(\tR\tjournalId2b\n" +
	"\x10LedgerAccounting\x12N\n" +
	"\x0fPostDoubleEntry\x12\x1c.ledger.v1.LedgerPostRequest\x1a\x1d.ledger.v1.LedgerPostResponseBLZJgithub.com/ai-crypto-onramp/transaction-orchestrator/internal/pb/ledger;pbb\x06proto3"

var (
	file_ledger_proto_rawDescOnce sync.Once
	file_ledger_proto_rawDescData []byte
)

func file_ledger_proto_rawDescGZIP() []byte {
	file_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_proto_rawDesc), len(file_ledger_proto_rawDesc)))
	})
	return file_ledger_proto_rawDescData
}

var file_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ledger_proto_goTypes = []any{
	(*LedgerPostRequest)(nil),  // 0: ledger.v1.LedgerPostRequest
	(*LedgerPostResponse)(nil), // 1: ledger.v1.LedgerPostResponse
}
var file_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.v1.LedgerAccounting.PostDoubleEntry:input_type -> ledger.v1.LedgerPostRequest
	1, // 1: ledger.v1.LedgerAccounting.PostDoubleEntry:output_type -> ledger.v1.LedgerPostResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ledger_proto_init() }
func file_ledger_proto_init() {
	if File_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_proto_rawDesc), len(file_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_proto_msgTypes,
	}.Build()
	File_ledger_proto = out.File
	file_ledger_proto_goTypes = nil
	file_ledger_proto_depIdxs = nil
}
