// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: ledger.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerAccounting_PostDoubleEntry_FullMethodName = "/ledger.v1.LedgerAccounting/PostDoubleEntry"
)

// LedgerAccountingClient is the client API for LedgerAccounting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LedgerAccounting posts a double-entry journal record for a completed
// purchase.
type LedgerAccountingClient interface {
	PostDoubleEntry(ctx context.Context, in *LedgerPostRequest, opts ...grpc.CallOption) (*LedgerPostResponse, error)
}

type ledgerAccountingClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerAccountingClient(cc grpc.ClientConnInterface) LedgerAccountingClient {
	return &ledgerAccountingClient{cc}
}

func (c *ledgerAccountingClient) PostDoubleEntry(ctx context.Context, in *LedgerPostRequest, opts ...grpc.CallOption) (*LedgerPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerPostResponse)
	err := c.cc.Invoke(ctx, LedgerAccounting_PostDoubleEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerAccountingServer is the server API for LedgerAccounting service.
// All implementations must embed UnimplementedLedgerAccountingServer
// for forward compatibility.
//
// LedgerAccounting posts a double-entry journal record for a completed
// purchase.
type LedgerAccountingServer interface {
	PostDoubleEntry(context.Context, *LedgerPostRequest) (*LedgerPostResponse, error)
	mustEmbedUnimplementedLedgerAccountingServer()
}

// UnimplementedLedgerAccountingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerAccountingServer struct{}

func (UnimplementedLedgerAccountingServer) PostDoubleEntry(context.Context, *LedgerPostRequest) (*LedgerPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostDoubleEntry not implemented")
}
func (UnimplementedLedgerAccountingServer) mustEmbedUnimplementedLedgerAccountingServer() {}
func (UnimplementedLedgerAccountingServer) testEmbeddedByValue()                          {}

// UnsafeLedgerAccountingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerAccountingServer will
// result in compilation errors.
type UnsafeLedgerAccountingServer interface {
	mustEmbedUnimplementedLedgerAccountingServer()
}

func RegisterLedgerAccountingServer(s grpc.ServiceRegistrar, srv LedgerAccountingServer) {
	// If the following call panics, it indicates UnimplementedLedgerAccountingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerAccounting_ServiceDesc, srv)
}

func _LedgerAccounting_PostDoubleEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerAccountingServer).PostDoubleEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerAccounting_PostDoubleEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerAccountingServer).PostDoubleEntry(ctx, req.(*LedgerPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerAccounting_ServiceDesc is the grpc.ServiceDesc for LedgerAccounting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerAccounting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerAccounting",
	HandlerType: (*LedgerAccountingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostDoubleEntry",
			Handler:    _LedgerAccounting_PostDoubleEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger.proto",
}
