// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: policy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyRiskEngine_Evaluate_FullMethodName = "/policy.v1.PolicyRiskEngine/Evaluate"
)

// PolicyRiskEngineClient is the client API for PolicyRiskEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyRiskEngine evaluates a purchase request against risk/compliance
// policy before any funds move.
type PolicyRiskEngineClient interface {
	// Evaluate returns an allow/deny decision for the given purchase request.
	Evaluate(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
}

type policyRiskEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyRiskEngineClient(cc grpc.ClientConnInterface) PolicyRiskEngineClient {
	return &policyRiskEngineClient{cc}
}

func (c *policyRiskEngineClient) Evaluate(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, PolicyRiskEngine_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyRiskEngineServer is the server API for PolicyRiskEngine service.
// All implementations must embed UnimplementedPolicyRiskEngineServer
// for forward compatibility.
//
// PolicyRiskEngine evaluates a purchase request against risk/compliance
// policy before any funds move.
type PolicyRiskEngineServer interface {
	// Evaluate returns an allow/deny decision for the given purchase request.
	Evaluate(context.Context, *PolicyRequest) (*PolicyResponse, error)
	mustEmbedUnimplementedPolicyRiskEngineServer()
}

// UnimplementedPolicyRiskEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyRiskEngineServer struct{}

func (UnimplementedPolicyRiskEngineServer) Evaluate(context.Context, *PolicyRequest) (*PolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedPolicyRiskEngineServer) mustEmbedUnimplementedPolicyRiskEngineServer() {}
func (UnimplementedPolicyRiskEngineServer) testEmbeddedByValue()                          {}

// UnsafePolicyRiskEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyRiskEngineServer will
// result in compilation errors.
type UnsafePolicyRiskEngineServer interface {
	mustEmbedUnimplementedPolicyRiskEngineServer()
}

func RegisterPolicyRiskEngineServer(s grpc.ServiceRegistrar, srv PolicyRiskEngineServer) {
	// If the following call panics, it indicates UnimplementedPolicyRiskEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyRiskEngine_ServiceDesc, srv)
}

func _PolicyRiskEngine_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyRiskEngineServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyRiskEngine_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyRiskEngineServer).Evaluate(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyRiskEngine_ServiceDesc is the grpc.ServiceDesc for PolicyRiskEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyRiskEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.v1.PolicyRiskEngine",
	HandlerType: (*PolicyRiskEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _PolicyRiskEngine_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy.proto",
}
