// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: payment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentOrchestration_Authorize_FullMethodName         = "/payment.v1.PaymentOrchestration/Authorize"
	PaymentOrchestration_Capture_FullMethodName           = "/payment.v1.PaymentOrchestration/Capture"
	PaymentOrchestration_VoidAuthorization_FullMethodName = "/payment.v1.PaymentOrchestration/VoidAuthorization"
	PaymentOrchestration_Refund_FullMethodName            = "/payment.v1.PaymentOrchestration/Refund"
)

// PaymentOrchestrationClient is the client API for PaymentOrchestration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentOrchestration authorizes and captures fiat for a purchase.
type PaymentOrchestrationClient interface {
	Authorize(ctx context.Context, in *PaymentAuthorizeRequest, opts ...grpc.CallOption) (*PaymentAuthorizeResponse, error)
	Capture(ctx context.Context, in *PaymentCaptureRequest, opts ...grpc.CallOption) (*PaymentCaptureResponse, error)
	VoidAuthorization(ctx context.Context, in *PaymentVoidRequest, opts ...grpc.CallOption) (*PaymentVoidResponse, error)
	Refund(ctx context.Context, in *PaymentRefundRequest, opts ...grpc.CallOption) (*PaymentRefundResponse, error)
}

type paymentOrchestrationClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentOrchestrationClient(cc grpc.ClientConnInterface) PaymentOrchestrationClient {
	return &paymentOrchestrationClient{cc}
}

func (c *paymentOrchestrationClient) Authorize(ctx context.Context, in *PaymentAuthorizeRequest, opts ...grpc.CallOption) (*PaymentAuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentAuthorizeResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestration_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestrationClient) Capture(ctx context.Context, in *PaymentCaptureRequest, opts ...grpc.CallOption) (*PaymentCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentCaptureResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestration_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestrationClient) VoidAuthorization(ctx context.Context, in *PaymentVoidRequest, opts ...grpc.CallOption) (*PaymentVoidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentVoidResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestration_VoidAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentOrchestrationClient) Refund(ctx context.Context, in *PaymentRefundRequest, opts ...grpc.CallOption) (*PaymentRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRefundResponse)
	err := c.cc.Invoke(ctx, PaymentOrchestration_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentOrchestrationServer is the server API for PaymentOrchestration service.
// All implementations must embed UnimplementedPaymentOrchestrationServer
// for forward compatibility.
//
// PaymentOrchestration authorizes and captures fiat for a purchase.
type PaymentOrchestrationServer interface {
	Authorize(context.Context, *PaymentAuthorizeRequest) (*PaymentAuthorizeResponse, error)
	Capture(context.Context, *PaymentCaptureRequest) (*PaymentCaptureResponse, error)
	VoidAuthorization(context.Context, *PaymentVoidRequest) (*PaymentVoidResponse, error)
	Refund(context.Context, *PaymentRefundRequest) (*PaymentRefundResponse, error)
	mustEmbedUnimplementedPaymentOrchestrationServer()
}

// UnimplementedPaymentOrchestrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentOrchestrationServer struct{}

func (UnimplementedPaymentOrchestrationServer) Authorize(context.Context, *PaymentAuthorizeRequest) (*PaymentAuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedPaymentOrchestrationServer) Capture(context.Context, *PaymentCaptureRequest) (*PaymentCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedPaymentOrchestrationServer) VoidAuthorization(context.Context, *PaymentVoidRequest) (*PaymentVoidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoidAuthorization not implemented")
}
func (UnimplementedPaymentOrchestrationServer) Refund(context.Context, *PaymentRefundRequest) (*PaymentRefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedPaymentOrchestrationServer) mustEmbedUnimplementedPaymentOrchestrationServer() {}
func (UnimplementedPaymentOrchestrationServer) testEmbeddedByValue()                              {}

// UnsafePaymentOrchestrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentOrchestrationServer will
// result in compilation errors.
type UnsafePaymentOrchestrationServer interface {
	mustEmbedUnimplementedPaymentOrchestrationServer()
}

func RegisterPaymentOrchestrationServer(s grpc.ServiceRegistrar, srv PaymentOrchestrationServer) {
	// If the following call panics, it indicates UnimplementedPaymentOrchestrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentOrchestration_ServiceDesc, srv)
}

func _PaymentOrchestration_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestrationServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestration_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestrationServer).Authorize(ctx, req.(*PaymentAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestration_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestrationServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestration_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestrationServer).Capture(ctx, req.(*PaymentCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestration_VoidAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentVoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestrationServer).VoidAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestration_VoidAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestrationServer).VoidAuthorization(ctx, req.(*PaymentVoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentOrchestration_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentOrchestrationServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentOrchestration_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentOrchestrationServer).Refund(ctx, req.(*PaymentRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentOrchestration_ServiceDesc is the grpc.ServiceDesc for PaymentOrchestration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentOrchestration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentOrchestration",
	HandlerType: (*PaymentOrchestrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _PaymentOrchestration_Authorize_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _PaymentOrchestration_Capture_Handler,
		},
		{
			MethodName: "VoidAuthorization",
			Handler:    _PaymentOrchestration_VoidAuthorization_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _PaymentOrchestration_Refund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
