// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentAuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,3,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	Rail          string                 `protobuf:"bytes,6,opt,name=rail,proto3" json:"rail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentAuthorizeRequest) Reset() {
	*x = PaymentAuthorizeRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthorizeRequest) ProtoMessage() {}

func (x *PaymentAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*PaymentAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentAuthorizeRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PaymentAuthorizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentAuthorizeRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *PaymentAuthorizeRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentAuthorizeRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *PaymentAuthorizeRequest) GetRail() string {
	if x != nil {
		return x.Rail
	}
	return ""
}

type PaymentAuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentAuthorizeResponse) Reset() {
	*x = PaymentAuthorizeResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAuthorizeResponse) ProtoMessage() {}

func (x *PaymentAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*PaymentAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentAuthorizeResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type PaymentCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	AuthId        string                 `protobuf:"bytes,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCaptureRequest) Reset() {
	*x = PaymentCaptureRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCaptureRequest) ProtoMessage() {}

func (x *PaymentCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCaptureRequest.ProtoReflect.Descriptor instead.
func (*PaymentCaptureRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentCaptureRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PaymentCaptureRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *PaymentCaptureRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentCaptureRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type PaymentCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptureId     string                 `protobuf:"bytes,1,opt,name=capture_id,json=captureId,proto3" json:"capture_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCaptureResponse) Reset() {
	*x = PaymentCaptureResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCaptureResponse) ProtoMessage() {}

func (x *PaymentCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCaptureResponse.ProtoReflect.Descriptor instead.
func (*PaymentCaptureResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCaptureResponse) GetCaptureId() string {
	if x != nil {
		return x.CaptureId
	}
	return ""
}

type PaymentVoidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	AuthId        string                 `protobuf:"bytes,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentVoidRequest) Reset() {
	*x = PaymentVoidRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentVoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentVoidRequest) ProtoMessage() {}

func (x *PaymentVoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentVoidRequest.ProtoReflect.Descriptor instead.
func (*PaymentVoidRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentVoidRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PaymentVoidRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type PaymentVoidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentVoidResponse) Reset() {
	*x = PaymentVoidResponse{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentVoidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentVoidResponse) ProtoMessage() {}

func (x *PaymentVoidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentVoidResponse.ProtoReflect.Descriptor instead.
func (*PaymentVoidResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

type PaymentRefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	CaptureId     string                 `protobuf:"bytes,2,opt,name=capture_id,json=captureId,proto3" json:"capture_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRefundRequest) Reset() {
	*x = PaymentRefundRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRefundRequest) ProtoMessage() {}

func (x *PaymentRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRefundRequest.ProtoReflect.Descriptor instead.
func (*PaymentRefundRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentRefundRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *PaymentRefundRequest) GetCaptureId() string {
	if x != nil {
		return x.CaptureId
	}
	return ""
}

func (x *PaymentRefundRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentRefundRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type PaymentRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRefundResponse) Reset() {
	*x = PaymentRefundResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRefundResponse) ProtoMessage() {}

func (x *PaymentRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRefundResponse.ProtoReflect.Descriptor instead.
func (*PaymentRefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\n" +
	"payment.v1\"\xa4\x01\n" +
	"\x17PaymentAuthorizeRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bquote_id\x18\x03 \x01(\tR\aquoteId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x05 \x01(\tR\x05asset\x12\x12\n" +
	"\x04rail\x18\x06 \x01(\tR\x04rail\"3\n" +
	"\x18PaymentAuthorizeResponse\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\"s\n" +
	"\x15PaymentCaptureRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\tR\x06authId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\"7\n" +
	"\x16PaymentCaptureResponse\x12\x1d\n" +
	"\n" +
	"capture_id\x18\x01 \x01(\tR\tcaptureId\"B\n" +
	"\x12PaymentVoidRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\tR\x06authId\"\x15\n" +
	"\x13PaymentVoidResponse\"x\n" +
	"\x14PaymentRefundRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x1d\n" +
	"\n" +
	"capture_id\x18\x02 \x01(\tR\tcaptureId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\"\x17\n" +
	"\x15PaymentRefundResponse2\xe5\x02\n" +
	"\x14PaymentOrchestration\x12V\n" +
	"\tAuthorize\x12#.payment.v1.PaymentAuthorizeRequest\x1a$.payment.v1.PaymentAuthorizeResponse\x12P\n" +
	"\aCapture\x12!.payment.v1.PaymentCaptureRequest\x1a\".payment.v1.PaymentCaptureResponse\x12T\n" +
	"\x11VoidAuthorization\x12\x1e.payment.v1.PaymentVoidRequest\x1a\x1f.payment.v1.PaymentVoidResponse\x12M\n" +
	"\x06Refund\x12 .payment.v1.PaymentRefundRequest\x1a!.payment.v1.PaymentRefundResponseBMZKgithub.com/ai-crypto-onramp/transaction-orchestrator/internal/pb/payment;pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(*PaymentAuthorizeRequest)(nil),  // 0: payment.v1.PaymentAuthorizeRequest
	(*PaymentAuthorizeResponse)(nil), // 1: payment.v1.PaymentAuthorizeResponse
	(*PaymentCaptureRequest)(nil),    // 2: payment.v1.PaymentCaptureRequest
	(*PaymentCaptureResponse)(nil),   // 3: payment.v1.PaymentCaptureResponse
	(*PaymentVoidRequest)(nil),       // 4: payment.v1.PaymentVoidRequest
	(*PaymentVoidResponse)(nil),      // 5: payment.v1.PaymentVoidResponse
	(*PaymentRefundRequest)(nil),     // 6: payment.v1.PaymentRefundRequest
	(*PaymentRefundResponse)(nil),    // 7: payment.v1.PaymentRefundResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentOrchestration.Authorize:input_type -> payment.v1.PaymentAuthorizeRequest
	2, // 1: payment.v1.PaymentOrchestration.Capture:input_type -> payment.v1.PaymentCaptureRequest
	4, // 2: payment.v1.PaymentOrchestration.VoidAuthorization:input_type -> payment.v1.PaymentVoidRequest
	6, // 3: payment.v1.PaymentOrchestration.Refund:input_type -> payment.v1.PaymentRefundRequest
	1, // 4: payment.v1.PaymentOrchestration.Authorize:output_type -> payment.v1.PaymentAuthorizeResponse
	3, // 5: payment.v1.PaymentOrchestration.Capture:output_type -> payment.v1.PaymentCaptureResponse
	5, // 6: payment.v1.PaymentOrchestration.VoidAuthorization:output_type -> payment.v1.PaymentVoidResponse
	7, // 7: payment.v1.PaymentOrchestration.Refund:output_type -> payment.v1.PaymentRefundResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
